import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/header/Header";
import ProviderWrapper from "@/components/ProviderWrapper";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <ProviderWrapper>
          <Header />
          {children}
          <Toaster position="top-right" reverseOrder={true} />
        </ProviderWrapper>
      </body>
    </html>
  );
}
